"use client"
import React from 'react';
import styles from '../styles/Instructions.module.css';

interface InstructionsProps {
    handleUserStoryInput : Function
}

const Instructions: React.FC<InstructionsProps> = ({handleUserStoryInput}) => {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Mystery Game Instructions</h1>
      <p className={styles.description}>
        Welcome to our intriguing mystery game! You’ll be tasked with solving a thrilling case by providing detailed information about your day. Your goal is to help us piece together clues and identify the thief. Here’s what we need from you:
      </p>
      <ul className={styles.list}>
        <li><strong>Whom did you meet?</strong> Describe the individuals you encountered throughout the day.</li>
        <li><strong>What did they do?</strong> Share what activities these people were involved in.</li>
        <li><strong>Circumstances/Instances?</strong> Provide any relevant circumstances or situations in which you met these individuals.</li>
        <li><strong>Where did you meet them?</strong> Specify the locations where these meetings took place.</li>
        <li><strong>When did you meet them?</strong> Note the times you interacted with these people.</li>
      </ul>
      <p className={styles.description}>
        The story you’ll be working with is generated by AI, ensuring a unique and exciting mystery each time you play. Use the clues from your observations to deduce the thief’s identity.
      </p>
      <button className={styles.button} onClick={() => handleUserStoryInput('ownStory')}>
        Start with your own creative inputs
      </button>
      <button className={styles.button} onClick={() => handleUserStoryInput('aiStory')}>
        Start with AI-generated inputs
      </button>
    </div>
  );
};

export default Instructions;
