"use client"
import React from 'react';
import styles from '../styles/Instructions.module.css';

interface InstructionsProps {
    handleUserStoryInput : Function
}

const Instructions: React.FC<InstructionsProps> = ({handleUserStoryInput}) => {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>How to play Mystery Trails</h1>
      <p className={styles.description}>
        Welcome to Mystery trails! Here you’ll be tasked with solving a thrilling case, which happens to arise from the detailed information about your day or experience, that you are gonna enter shortly. </p><br />
        <p style={{fontWeight:'bold', color:'white'}}>Your final goal is to piece together the clues and identify the culprit, that is gonna be one of the people whom you described that you have met.</p> <br /> 
        <p className={styles.description} style={{marginBottom: '1rem'}}> Ready to get started ? 
          Here’s what we need from you:
      </p>
      <ul className={styles.list}>
        <li><strong>Describe a day of your life (maybe today)</strong><br /> More the details, Interesting is the case.</li>
        <li><strong>Include names of people whom you have met</strong><br /> Even if you dont know them, you can choose to nickname them.</li>
        <li><strong>Try to include scenarios / circumstances that happened ?</strong><br /> Try adding appropriate circumstances or situations.</li>
        <li><strong>You can choose to include places</strong><br />Optionally, you can choose to specify the locations.</li>
      </ul>
      <p className={styles.description}>
        The story you’ll be working with is generated by AI, ensuring a unique and exciting mystery each time you play. Use the clues from your observations to deduce the thief’s identity.
      </p>
      <button className={styles.button} onClick={() => handleUserStoryInput('ownStory')}>
        Start with your own creative inputs
      </button>
    </div>
  );
};

export default Instructions;
